//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34014
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPiaoBao.DomesticTicket.Domain.ZKInsurance {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ZKInsurance.JtywInsServiceSoap")]
    public interface JtywInsServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PolicyOperate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode PolicyOperate(string xmlData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PolicyOperate_Test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode PolicyOperate_Test(string xmlData);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JtywInsServiceSoapChannel : BPiaoBao.DomesticTicket.Domain.ZKInsurance.JtywInsServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JtywInsServiceSoapClient : System.ServiceModel.ClientBase<BPiaoBao.DomesticTicket.Domain.ZKInsurance.JtywInsServiceSoap>, BPiaoBao.DomesticTicket.Domain.ZKInsurance.JtywInsServiceSoap {
        
        public JtywInsServiceSoapClient() {
        }
        
        public JtywInsServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JtywInsServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JtywInsServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JtywInsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.XmlNode PolicyOperate(string xmlData) {
            return base.Channel.PolicyOperate(xmlData);
        }
        
        public System.Xml.XmlNode PolicyOperate_Test(string xmlData) {
            return base.Channel.PolicyOperate_Test(xmlData);
        }
    }
}
