//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPiaoBao.Client.DomesticTicket.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BPiaoBao.Client.DomesticTicket.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 正在通信请稍等... 的本地化字符串。
        /// </summary>
        internal static string CommuinationBusy {
            get {
                return ResourceManager.GetString("CommuinationBusy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10012 的本地化字符串。
        /// </summary>
        internal static string OrderCode {
            get {
                return ResourceManager.GetString("OrderCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 轻松管理订单信息 的本地化字符串。
        /// </summary>
        internal static string OrderDesc {
            get {
                return ResourceManager.GetString("OrderDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单管理 的本地化字符串。
        /// </summary>
        internal static string OrderName {
            get {
                return ResourceManager.GetString("OrderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10011 的本地化字符串。
        /// </summary>
        internal static string PNRCode {
            get {
                return ResourceManager.GetString("PNRCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快捷方便查询航班 的本地化字符串。
        /// </summary>
        internal static string PNRDesc {
            get {
                return ResourceManager.GetString("PNRDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 PNR下单 的本地化字符串。
        /// </summary>
        internal static string PNRName {
            get {
                return ResourceManager.GetString("PNRName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 1 的本地化字符串。
        /// </summary>
        internal static string ProjectCode {
            get {
                return ResourceManager.GetString("ProjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 国内机票 的本地化字符串。
        /// </summary>
        internal static string ProjectName {
            get {
                return ResourceManager.GetString("ProjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 0.1.1.1 的本地化字符串。
        /// </summary>
        internal static string ProjectVersion {
            get {
                return ResourceManager.GetString("ProjectVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表分析 的本地化字符串。
        /// </summary>
        internal static string ReportAnalysis {
            get {
                return ResourceManager.GetString("ReportAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 100132 的本地化字符串。
        /// </summary>
        internal static string ReportAnalysisCode {
            get {
                return ResourceManager.GetString("ReportAnalysisCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 10013 的本地化字符串。
        /// </summary>
        internal static string ReportCode {
            get {
                return ResourceManager.GetString("ReportCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 准确管理报表信息 的本地化字符串。
        /// </summary>
        internal static string ReportDesc {
            get {
                return ResourceManager.GetString("ReportDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 报表管理 的本地化字符串。
        /// </summary>
        internal static string ReportName {
            get {
                return ResourceManager.GetString("ReportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 机票总表 的本地化字符串。
        /// </summary>
        internal static string TicketTableName {
            get {
                return ResourceManager.GetString("TicketTableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 100131 的本地化字符串。
        /// </summary>
        internal static string TickTableCode {
            get {
                return ResourceManager.GetString("TickTableCode", resourceCulture);
            }
        }
    }
}
