//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.19075
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPiaoBao.DomesticTicket.Platforms.webTodayPolicy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://policy.jinri.cn/", ConfigurationName="webTodayPolicy.JinRiRateServerSoap")]
    public interface JinRiRateServerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/GetRateList", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetRateList(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/GetRateListByPNR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetRateListByPNR(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/GetRateByPolicyID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetRateByPolicyID(string data);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JinRiRateServerSoapChannel : BPiaoBao.DomesticTicket.Platforms.webTodayPolicy.JinRiRateServerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JinRiRateServerSoapClient : System.ServiceModel.ClientBase<BPiaoBao.DomesticTicket.Platforms.webTodayPolicy.JinRiRateServerSoap>, BPiaoBao.DomesticTicket.Platforms.webTodayPolicy.JinRiRateServerSoap {
        
        public JinRiRateServerSoapClient() {
        }
        
        public JinRiRateServerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JinRiRateServerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JinRiRateServerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JinRiRateServerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetRateList(string data) {
            return base.Channel.GetRateList(data);
        }
        
        public string GetRateListByPNR(string data) {
            return base.Channel.GetRateListByPNR(data);
        }
        
        public string GetRateByPolicyID(string data) {
            return base.Channel.GetRateByPolicyID(data);
        }
    }
}
