//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.19075
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPiaoBao.DomesticTicket.Platforms.webTodayOrder {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://policy.jinri.cn/", ConfigurationName="webTodayOrder.JinRiOrderServerSoap")]
    public interface JinRiOrderServerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/CreateOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateOrder(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/CreateOrderByPNR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateOrderByPNR(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/ReCreateOrderByPNR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReCreateOrderByPNR(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/GetOrderInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetOrderInfo(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/GetOrderInfoByTicketNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetOrderInfoByTicketNo(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/CreateChdPNR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateChdPNR(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/CancelOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CancelOrder(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/GaiqianOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GaiqianOrder(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/GetGaiqianOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetGaiqianOrder(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/TuiFeiOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string TuiFeiOrder(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/GetReturnOrderInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetReturnOrderInfo(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/RiseCabin", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RiseCabin(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/GetRaiseOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetRaiseOrder(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/CreateJourney", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateJourney(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/GetJourneyTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetJourneyTicket(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/GetOfficeId", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetOfficeId(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/UpdateOrderByPause", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string UpdateOrderByPause(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/CheckPNR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckPNR(string xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://policy.jinri.cn/CheckSiteByPnr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CheckSiteByPnr(string xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JinRiOrderServerSoapChannel : BPiaoBao.DomesticTicket.Platforms.webTodayOrder.JinRiOrderServerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JinRiOrderServerSoapClient : System.ServiceModel.ClientBase<BPiaoBao.DomesticTicket.Platforms.webTodayOrder.JinRiOrderServerSoap>, BPiaoBao.DomesticTicket.Platforms.webTodayOrder.JinRiOrderServerSoap {
        
        public JinRiOrderServerSoapClient() {
        }
        
        public JinRiOrderServerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JinRiOrderServerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JinRiOrderServerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JinRiOrderServerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CreateOrder(string xml) {
            return base.Channel.CreateOrder(xml);
        }
        
        public string CreateOrderByPNR(string xml) {
            return base.Channel.CreateOrderByPNR(xml);
        }
        
        public string ReCreateOrderByPNR(string xml) {
            return base.Channel.ReCreateOrderByPNR(xml);
        }
        
        public string GetOrderInfo(string xml) {
            return base.Channel.GetOrderInfo(xml);
        }
        
        public string GetOrderInfoByTicketNo(string xml) {
            return base.Channel.GetOrderInfoByTicketNo(xml);
        }
        
        public string CreateChdPNR(string xml) {
            return base.Channel.CreateChdPNR(xml);
        }
        
        public string CancelOrder(string xml) {
            return base.Channel.CancelOrder(xml);
        }
        
        public string GaiqianOrder(string xml) {
            return base.Channel.GaiqianOrder(xml);
        }
        
        public string GetGaiqianOrder(string xml) {
            return base.Channel.GetGaiqianOrder(xml);
        }
        
        public string TuiFeiOrder(string xml) {
            return base.Channel.TuiFeiOrder(xml);
        }
        
        public string GetReturnOrderInfo(string xml) {
            return base.Channel.GetReturnOrderInfo(xml);
        }
        
        public string RiseCabin(string xml) {
            return base.Channel.RiseCabin(xml);
        }
        
        public string GetRaiseOrder(string xml) {
            return base.Channel.GetRaiseOrder(xml);
        }
        
        public string CreateJourney(string xml) {
            return base.Channel.CreateJourney(xml);
        }
        
        public string GetJourneyTicket(string xml) {
            return base.Channel.GetJourneyTicket(xml);
        }
        
        public string GetOfficeId(string xml) {
            return base.Channel.GetOfficeId(xml);
        }
        
        public string UpdateOrderByPause(string xml) {
            return base.Channel.UpdateOrderByPause(xml);
        }
        
        public string CheckPNR(string xml) {
            return base.Channel.CheckPNR(xml);
        }
        
        public string CheckSiteByPnr(string xml) {
            return base.Channel.CheckSiteByPnr(xml);
        }
    }
}
