//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.19075
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPiaoBao.DomesticTicket.Platforms.web8000yi {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="web8000yi.W8000YServiceSoap")]
    public interface W8000YServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlreadyDisposalSynchronizationNew_All", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AlreadyDisposalSynchronizationNew_All(string name, string pwd, string datetime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlreadyDisposalSynchronizationNew_All_V2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AlreadyDisposalSynchronizationNew_All_V2(string name, string pwd, string datetime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlreadyDisposalSynchronizationNew_All_GZip", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AlreadyDisposalSynchronizationNew_All_GZip(string name, string pwd, string datetime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlreadyDisposalSynchronizationNewSpecial_All", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AlreadyDisposalSynchronizationNewSpecial_All(string name, string pwd, string datetime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AlreadyDisposalSynchronizationNewFD_All", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AlreadyDisposalSynchronizationNewFD_All(string name, string pwd, string datetime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPExactitude", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SPExactitude(string name, string pwd, string fromCity, string tocity, string Airco, string airNo, string Airbunk, string airtime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPlantPriceData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPlantPriceData(string Name, string Pwd, string ZKId, string AirCo, string FromCity, string ToCity, string CW, int IsSpecial, string UpdateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDeletePolicy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDeletePolicy(string name, string pwd, string datetime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SPbyPNRNote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SPbyPNRNote(string name, string pwd, string pnrCode, int isSpecial, string pnrInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreatOrderNewByPNRNote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CreatOrderNewByPNRNote(string name, string pwd, string pnrCode, string pid, string pnrInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreatOrderNew_ByPNRNoteV2", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CreatOrderNew_ByPNRNoteV2(string name, string pwd, string pnrCode, string pid, string userRtInfo, string IshPNR);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreatOrderNew_ByPNRNoteV3", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CreatOrderNew_ByPNRNoteV3(string name, string pwd, string pnrCode, string pid, string userRtInfo, string IshPNR, string LinkMan, string LinkPhone);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnOrderOutTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string returnOrderOutTicket(string name, string pwd, string orderguid, string outremark);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateCHDPnr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreateCHDPnr(string name, string pwd, string fromcitys, string Tocitys, string Dates, string ToTimes, string CabinSeats, string OpportunityForPeople, string NoDocuments, string Airlines, string FlightNumber, string birthdays);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateOrderNewByCHD", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CreateOrderNewByCHD(string name, string pwd, string chdPnr, string adultOrderGuid, string A1);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderPayOutTicketAndPly", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet OrderPayOutTicketAndPly(string name, string pwd, string ordertime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/PaySignOn", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string PaySignOn(string name, string pwd, string emAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutomatismPay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet AutomatismPay(string name, string pwd, string orderguid, string payAccount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetWhyByOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetWhyByOrder(string name, string pwd, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderRGIInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string OrderRGIInfo(string name, string pwd, string porderguid, string ticketNo, string whyId, string type);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnTicekNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet ReturnTicekNo(string name, string pwd, string orderid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderGuidRGIDetails", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet OrderGuidRGIDetails(string name, string pwd, string orderid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CancelOrderNew", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CancelOrderNew(string name, string pwd, string orderid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/returnOrderState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet returnOrderState(string name, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderGuidPayOutTicketAndPly", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet OrderGuidPayOutTicketAndPly(string name, string pwd, string orderguid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface W8000YServiceSoapChannel : BPiaoBao.DomesticTicket.Platforms.web8000yi.W8000YServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class W8000YServiceSoapClient : System.ServiceModel.ClientBase<BPiaoBao.DomesticTicket.Platforms.web8000yi.W8000YServiceSoap>, BPiaoBao.DomesticTicket.Platforms.web8000yi.W8000YServiceSoap {
        
        public W8000YServiceSoapClient() {
        }
        
        public W8000YServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public W8000YServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public W8000YServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public W8000YServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet AlreadyDisposalSynchronizationNew_All(string name, string pwd, string datetime) {
            return base.Channel.AlreadyDisposalSynchronizationNew_All(name, pwd, datetime);
        }
        
        public System.Data.DataSet AlreadyDisposalSynchronizationNew_All_V2(string name, string pwd, string datetime) {
            return base.Channel.AlreadyDisposalSynchronizationNew_All_V2(name, pwd, datetime);
        }
        
        public string AlreadyDisposalSynchronizationNew_All_GZip(string name, string pwd, string datetime) {
            return base.Channel.AlreadyDisposalSynchronizationNew_All_GZip(name, pwd, datetime);
        }
        
        public System.Data.DataSet AlreadyDisposalSynchronizationNewSpecial_All(string name, string pwd, string datetime) {
            return base.Channel.AlreadyDisposalSynchronizationNewSpecial_All(name, pwd, datetime);
        }
        
        public System.Data.DataSet AlreadyDisposalSynchronizationNewFD_All(string name, string pwd, string datetime) {
            return base.Channel.AlreadyDisposalSynchronizationNewFD_All(name, pwd, datetime);
        }
        
        public System.Data.DataSet SPExactitude(string name, string pwd, string fromCity, string tocity, string Airco, string airNo, string Airbunk, string airtime) {
            return base.Channel.SPExactitude(name, pwd, fromCity, tocity, Airco, airNo, Airbunk, airtime);
        }
        
        public System.Data.DataSet GetPlantPriceData(string Name, string Pwd, string ZKId, string AirCo, string FromCity, string ToCity, string CW, int IsSpecial, string UpdateTime) {
            return base.Channel.GetPlantPriceData(Name, Pwd, ZKId, AirCo, FromCity, ToCity, CW, IsSpecial, UpdateTime);
        }
        
        public System.Data.DataSet GetDeletePolicy(string name, string pwd, string datetime) {
            return base.Channel.GetDeletePolicy(name, pwd, datetime);
        }
        
        public System.Data.DataSet SPbyPNRNote(string name, string pwd, string pnrCode, int isSpecial, string pnrInfo) {
            return base.Channel.SPbyPNRNote(name, pwd, pnrCode, isSpecial, pnrInfo);
        }
        
        public System.Data.DataSet CreatOrderNewByPNRNote(string name, string pwd, string pnrCode, string pid, string pnrInfo) {
            return base.Channel.CreatOrderNewByPNRNote(name, pwd, pnrCode, pid, pnrInfo);
        }
        
        public System.Data.DataSet CreatOrderNew_ByPNRNoteV2(string name, string pwd, string pnrCode, string pid, string userRtInfo, string IshPNR) {
            return base.Channel.CreatOrderNew_ByPNRNoteV2(name, pwd, pnrCode, pid, userRtInfo, IshPNR);
        }
        
        public System.Data.DataSet CreatOrderNew_ByPNRNoteV3(string name, string pwd, string pnrCode, string pid, string userRtInfo, string IshPNR, string LinkMan, string LinkPhone) {
            return base.Channel.CreatOrderNew_ByPNRNoteV3(name, pwd, pnrCode, pid, userRtInfo, IshPNR, LinkMan, LinkPhone);
        }
        
        public string returnOrderOutTicket(string name, string pwd, string orderguid, string outremark) {
            return base.Channel.returnOrderOutTicket(name, pwd, orderguid, outremark);
        }
        
        public string CreateCHDPnr(string name, string pwd, string fromcitys, string Tocitys, string Dates, string ToTimes, string CabinSeats, string OpportunityForPeople, string NoDocuments, string Airlines, string FlightNumber, string birthdays) {
            return base.Channel.CreateCHDPnr(name, pwd, fromcitys, Tocitys, Dates, ToTimes, CabinSeats, OpportunityForPeople, NoDocuments, Airlines, FlightNumber, birthdays);
        }
        
        public System.Data.DataSet CreateOrderNewByCHD(string name, string pwd, string chdPnr, string adultOrderGuid, string A1) {
            return base.Channel.CreateOrderNewByCHD(name, pwd, chdPnr, adultOrderGuid, A1);
        }
        
        public System.Data.DataSet OrderPayOutTicketAndPly(string name, string pwd, string ordertime) {
            return base.Channel.OrderPayOutTicketAndPly(name, pwd, ordertime);
        }
        
        public string PaySignOn(string name, string pwd, string emAccount) {
            return base.Channel.PaySignOn(name, pwd, emAccount);
        }
        
        public System.Data.DataSet AutomatismPay(string name, string pwd, string orderguid, string payAccount) {
            return base.Channel.AutomatismPay(name, pwd, orderguid, payAccount);
        }
        
        public System.Data.DataSet GetWhyByOrder(string name, string pwd, string type) {
            return base.Channel.GetWhyByOrder(name, pwd, type);
        }
        
        public string OrderRGIInfo(string name, string pwd, string porderguid, string ticketNo, string whyId, string type) {
            return base.Channel.OrderRGIInfo(name, pwd, porderguid, ticketNo, whyId, type);
        }
        
        public System.Data.DataSet ReturnTicekNo(string name, string pwd, string orderid) {
            return base.Channel.ReturnTicekNo(name, pwd, orderid);
        }
        
        public System.Data.DataSet OrderGuidRGIDetails(string name, string pwd, string orderid) {
            return base.Channel.OrderGuidRGIDetails(name, pwd, orderid);
        }
        
        public string CancelOrderNew(string name, string pwd, string orderid) {
            return base.Channel.CancelOrderNew(name, pwd, orderid);
        }
        
        public System.Data.DataSet returnOrderState(string name, string pwd) {
            return base.Channel.returnOrderState(name, pwd);
        }
        
        public System.Data.DataSet OrderGuidPayOutTicketAndPly(string name, string pwd, string orderguid) {
            return base.Channel.OrderGuidPayOutTicketAndPly(name, pwd, orderguid);
        }
    }
}
