//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JoveZhao.Framework.SMSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSService.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateXMLNode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int UpdateXMLNode(string nodeName, string nodeValue);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadXML", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReadXML();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReadXMLByName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ReadXMLByName(string Name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FastSendSMS", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int FastSendSMS(string TargetNo, string MsgContent);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetBalanceCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetBalanceCount();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : JoveZhao.Framework.SMSService.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<JoveZhao.Framework.SMSService.Service1Soap>, JoveZhao.Framework.SMSService.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int UpdateXMLNode(string nodeName, string nodeValue) {
            return base.Channel.UpdateXMLNode(nodeName, nodeValue);
        }
        
        public string ReadXML() {
            return base.Channel.ReadXML();
        }
        
        public string ReadXMLByName(string Name) {
            return base.Channel.ReadXMLByName(Name);
        }
        
        public int FastSendSMS(string TargetNo, string MsgContent) {
            return base.Channel.FastSendSMS(TargetNo, MsgContent);
        }
        
        public string GetBalanceCount() {
            return base.Channel.GetBalanceCount();
        }
    }
}
