// <auto-generated />
namespace BPiaoBao.DomesticTicket.EFRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class _201407281115 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201407281115));
        
        string IMigrationMetadata.Id
        {
            get { return "201407280316038_201407281115"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
