// <auto-generated />
namespace BPiaoBao.DomesticTicket.EFRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class _201407251158 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201407251158));
        
        string IMigrationMetadata.Id
        {
            get { return "201407250403553_201407251158"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
