// <auto-generated />
namespace BPiaoBao.DomesticTicket.EFRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class _201409161543 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201409161543));
        
        string IMigrationMetadata.Id
        {
            get { return "201409160804526_201409161543"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
