//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.19075
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPiaoBao.DomesticTicket.Platforms.web51book {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://203.88.210.234:113/", ConfigurationName="web51book._51bookServiceSoap")]
    public interface _51bookServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:113/bookGetPolicyData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet bookGetPolicyData(string AgencyCode, string SignCode, string departure, string arrival, string isIncludeSpecialPolicy, string isBusinessUnitPolicy, string page, string rowPerPage);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:113/booksynchronizePolicyData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet booksynchronizePolicyData(string AgencyCode, string SignCode, string lastUpdateTime, string returnRecordCount, string policyId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:113/bookGetPolicyDataByPNR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet bookGetPolicyDataByPNR(string AgencyCode, string PNRCode, string SignCode, string param1, string param2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:113/bookGetPolicyDataByPNRTxt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet bookGetPolicyDataByPNRTxt(string AgencyCode, string pnrTxt, string pataTxt, string SignCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:113/bookCreatePolicyOrderByPNR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet bookCreatePolicyOrderByPNR(string AgencyCode, string PNRCode, string policyId, string paymentReturnUrl, string notifiedUrl, string b2cCreatorCn, string SignCode, string param1, string param2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:113/bookCreatePolicyOrderByPNRTxt", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet bookCreatePolicyOrderByPNRTxt(string AgencyCode, string pnrTxt, string pataTxt, string policyId, string paymentReturnUrl, string notifiedUrl, string b2cCreatorCn, string SignCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:113/bookPayPolicyOrderByPNR", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet bookPayPolicyOrderByPNR(string AgencyCode, string OrderNo, string userName, string password, string SignCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:113/bookGetPolicyOrderStatusByOrderNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet bookGetPolicyOrderStatusByOrderNo(string AgencyCode, string orderNo, string statusType, string SignCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:113/bookgetPolicyOrderByOrderNo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet bookgetPolicyOrderByOrderNo(string AgencyCode, string sequenceNo, string sequenceNoType, string SignCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:113/bookApplyPolicyOrderRefund", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet bookApplyPolicyOrderRefund(string AgencyCode, string orderSequenceNo, string orderSequenceNoType, string actionType, string ticketNos, string segment, string logMassage, string refundAnnexDirPath, string refundNotifiedUrl, string param1, string param2, string param3, string SignCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:113/cancelOrderOrPnr", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet cancelOrderOrPnr(string opType, string AgencyCode, string SignCode, string sequenceNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:113/Test", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Test(string AgencyCode, string PNRCode, string policyId, string paymentReturnUrl, string notifiedUrl, string b2cCreatorCn, string SignCode, string param1, string param2);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface _51bookServiceSoapChannel : BPiaoBao.DomesticTicket.Platforms.web51book._51bookServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class _51bookServiceSoapClient : System.ServiceModel.ClientBase<BPiaoBao.DomesticTicket.Platforms.web51book._51bookServiceSoap>, BPiaoBao.DomesticTicket.Platforms.web51book._51bookServiceSoap {
        
        public _51bookServiceSoapClient() {
        }
        
        public _51bookServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public _51bookServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public _51bookServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public _51bookServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet bookGetPolicyData(string AgencyCode, string SignCode, string departure, string arrival, string isIncludeSpecialPolicy, string isBusinessUnitPolicy, string page, string rowPerPage) {
            return base.Channel.bookGetPolicyData(AgencyCode, SignCode, departure, arrival, isIncludeSpecialPolicy, isBusinessUnitPolicy, page, rowPerPage);
        }
        
        public System.Data.DataSet booksynchronizePolicyData(string AgencyCode, string SignCode, string lastUpdateTime, string returnRecordCount, string policyId) {
            return base.Channel.booksynchronizePolicyData(AgencyCode, SignCode, lastUpdateTime, returnRecordCount, policyId);
        }
        
        public System.Data.DataSet bookGetPolicyDataByPNR(string AgencyCode, string PNRCode, string SignCode, string param1, string param2) {
            return base.Channel.bookGetPolicyDataByPNR(AgencyCode, PNRCode, SignCode, param1, param2);
        }
        
        public System.Data.DataSet bookGetPolicyDataByPNRTxt(string AgencyCode, string pnrTxt, string pataTxt, string SignCode) {
            return base.Channel.bookGetPolicyDataByPNRTxt(AgencyCode, pnrTxt, pataTxt, SignCode);
        }
        
        public System.Data.DataSet bookCreatePolicyOrderByPNR(string AgencyCode, string PNRCode, string policyId, string paymentReturnUrl, string notifiedUrl, string b2cCreatorCn, string SignCode, string param1, string param2) {
            return base.Channel.bookCreatePolicyOrderByPNR(AgencyCode, PNRCode, policyId, paymentReturnUrl, notifiedUrl, b2cCreatorCn, SignCode, param1, param2);
        }
        
        public System.Data.DataSet bookCreatePolicyOrderByPNRTxt(string AgencyCode, string pnrTxt, string pataTxt, string policyId, string paymentReturnUrl, string notifiedUrl, string b2cCreatorCn, string SignCode) {
            return base.Channel.bookCreatePolicyOrderByPNRTxt(AgencyCode, pnrTxt, pataTxt, policyId, paymentReturnUrl, notifiedUrl, b2cCreatorCn, SignCode);
        }
        
        public System.Data.DataSet bookPayPolicyOrderByPNR(string AgencyCode, string OrderNo, string userName, string password, string SignCode) {
            return base.Channel.bookPayPolicyOrderByPNR(AgencyCode, OrderNo, userName, password, SignCode);
        }
        
        public System.Data.DataSet bookGetPolicyOrderStatusByOrderNo(string AgencyCode, string orderNo, string statusType, string SignCode) {
            return base.Channel.bookGetPolicyOrderStatusByOrderNo(AgencyCode, orderNo, statusType, SignCode);
        }
        
        public System.Data.DataSet bookgetPolicyOrderByOrderNo(string AgencyCode, string sequenceNo, string sequenceNoType, string SignCode) {
            return base.Channel.bookgetPolicyOrderByOrderNo(AgencyCode, sequenceNo, sequenceNoType, SignCode);
        }
        
        public System.Data.DataSet bookApplyPolicyOrderRefund(string AgencyCode, string orderSequenceNo, string orderSequenceNoType, string actionType, string ticketNos, string segment, string logMassage, string refundAnnexDirPath, string refundNotifiedUrl, string param1, string param2, string param3, string SignCode) {
            return base.Channel.bookApplyPolicyOrderRefund(AgencyCode, orderSequenceNo, orderSequenceNoType, actionType, ticketNos, segment, logMassage, refundAnnexDirPath, refundNotifiedUrl, param1, param2, param3, SignCode);
        }
        
        public System.Data.DataSet cancelOrderOrPnr(string opType, string AgencyCode, string SignCode, string sequenceNo) {
            return base.Channel.cancelOrderOrPnr(opType, AgencyCode, SignCode, sequenceNo);
        }
        
        public string Test(string AgencyCode, string PNRCode, string policyId, string paymentReturnUrl, string notifiedUrl, string b2cCreatorCn, string SignCode, string param1, string param2) {
            return base.Channel.Test(AgencyCode, PNRCode, policyId, paymentReturnUrl, notifiedUrl, b2cCreatorCn, SignCode, param1, param2);
        }
    }
}
