// <auto-generated />
namespace BPiaoBao.SystemSetting.EFRepository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class _201411251627 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201411251627));
        
        string IMigrationMetadata.Id
        {
            get { return "201411250827540_201411251627"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
