//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.19075
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPiaoBao.DomesticTicket.Platforms.webbaituo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", ConfigurationName="webbaituo.BaiTuoWebSoap")]
    public interface BaiTuoWebSoap {
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 TripType 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/GetAlterDomesticCabinZRateByParam", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.GetAlterDomesticCabinZRateByParamResponse GetAlterDomesticCabinZRateByParam(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetAlterDomesticCabinZRateByParamRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 xmlMessage 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/GetDomesticMatchNormalZRateList", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateListResponse GetDomesticMatchNormalZRateList(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateListRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 xmlMessage 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/GetDomesticMatchNormalZRateStr", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateStrResponse GetDomesticMatchNormalZRateStr(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateStrRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 xmlElement 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/GetInvalidationProviderListXML", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListXMLResponse GetInvalidationProviderListXML(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListXMLRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 xmlDoc 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/GetInvalidationProviderListSTR", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListSTRResponse GetInvalidationProviderListSTR(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListSTRRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 xeMessage 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/pnrCreateOrderEx", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExResponse pnrCreateOrderEx(BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 xeMessage 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/pnrCreateOrderExStr", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExStrResponse pnrCreateOrderExStr(BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExStrRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 AgentCode 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/getOrderInfo", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoResponse getOrderInfo(BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 xmlMessage 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/getOrderInfoXml", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoXmlResponse getOrderInfoXml(BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoXmlRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 XmlMessage 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/NotifyXml", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyXmlResponse NotifyXml(BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyXmlRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 Message 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/NotifyStr", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyStrResponse NotifyStr(BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyStrRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 xml 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/ApplyRefundOrder", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderResponse ApplyRefundOrder(BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 Message 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/ApplyRefundOrderStr", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderStrResponse ApplyRefundOrderStr(BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderStrRequest request);
        
        // CODEGEN: 命名空间 http://203.88.210.234:114/BaiTuoWeb.asmx 的元素名称 url 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:114/BaiTuoWeb.asmx/GetUrlData", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.GetUrlDataResponse GetUrlData(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetUrlDataRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlterDomesticCabinZRateByParamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlterDomesticCabinZRateByParam", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.GetAlterDomesticCabinZRateByParamRequestBody Body;
        
        public GetAlterDomesticCabinZRateByParamRequest() {
        }
        
        public GetAlterDomesticCabinZRateByParamRequest(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetAlterDomesticCabinZRateByParamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetAlterDomesticCabinZRateByParamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TripType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string TicketType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CoAgentOffice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CoUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CoUserPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string RQStartDateTime;
        
        public GetAlterDomesticCabinZRateByParamRequestBody() {
        }
        
        public GetAlterDomesticCabinZRateByParamRequestBody(string TripType, string TicketType, string CoAgentOffice, string CoUserName, string CoUserPwd, string RQStartDateTime) {
            this.TripType = TripType;
            this.TicketType = TicketType;
            this.CoAgentOffice = CoAgentOffice;
            this.CoUserName = CoUserName;
            this.CoUserPwd = CoUserPwd;
            this.RQStartDateTime = RQStartDateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlterDomesticCabinZRateByParamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlterDomesticCabinZRateByParamResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.GetAlterDomesticCabinZRateByParamResponseBody Body;
        
        public GetAlterDomesticCabinZRateByParamResponse() {
        }
        
        public GetAlterDomesticCabinZRateByParamResponse(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetAlterDomesticCabinZRateByParamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetAlterDomesticCabinZRateByParamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetAlterDomesticCabinZRateByParamResult;
        
        public GetAlterDomesticCabinZRateByParamResponseBody() {
        }
        
        public GetAlterDomesticCabinZRateByParamResponseBody(System.Xml.Linq.XElement GetAlterDomesticCabinZRateByParamResult) {
            this.GetAlterDomesticCabinZRateByParamResult = GetAlterDomesticCabinZRateByParamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomesticMatchNormalZRateListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomesticMatchNormalZRateList", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateListRequestBody Body;
        
        public GetDomesticMatchNormalZRateListRequest() {
        }
        
        public GetDomesticMatchNormalZRateListRequest(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetDomesticMatchNormalZRateListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement xmlMessage;
        
        public GetDomesticMatchNormalZRateListRequestBody() {
        }
        
        public GetDomesticMatchNormalZRateListRequestBody(System.Xml.Linq.XElement xmlMessage) {
            this.xmlMessage = xmlMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomesticMatchNormalZRateListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomesticMatchNormalZRateListResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateListResponseBody Body;
        
        public GetDomesticMatchNormalZRateListResponse() {
        }
        
        public GetDomesticMatchNormalZRateListResponse(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetDomesticMatchNormalZRateListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetDomesticMatchNormalZRateListResult;
        
        public GetDomesticMatchNormalZRateListResponseBody() {
        }
        
        public GetDomesticMatchNormalZRateListResponseBody(System.Xml.Linq.XElement GetDomesticMatchNormalZRateListResult) {
            this.GetDomesticMatchNormalZRateListResult = GetDomesticMatchNormalZRateListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomesticMatchNormalZRateStrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomesticMatchNormalZRateStr", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateStrRequestBody Body;
        
        public GetDomesticMatchNormalZRateStrRequest() {
        }
        
        public GetDomesticMatchNormalZRateStrRequest(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateStrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetDomesticMatchNormalZRateStrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlMessage;
        
        public GetDomesticMatchNormalZRateStrRequestBody() {
        }
        
        public GetDomesticMatchNormalZRateStrRequestBody(string xmlMessage) {
            this.xmlMessage = xmlMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomesticMatchNormalZRateStrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomesticMatchNormalZRateStrResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateStrResponseBody Body;
        
        public GetDomesticMatchNormalZRateStrResponse() {
        }
        
        public GetDomesticMatchNormalZRateStrResponse(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateStrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetDomesticMatchNormalZRateStrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDomesticMatchNormalZRateStrResult;
        
        public GetDomesticMatchNormalZRateStrResponseBody() {
        }
        
        public GetDomesticMatchNormalZRateStrResponseBody(string GetDomesticMatchNormalZRateStrResult) {
            this.GetDomesticMatchNormalZRateStrResult = GetDomesticMatchNormalZRateStrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvalidationProviderListXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvalidationProviderListXML", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListXMLRequestBody Body;
        
        public GetInvalidationProviderListXMLRequest() {
        }
        
        public GetInvalidationProviderListXMLRequest(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetInvalidationProviderListXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement xmlElement;
        
        public GetInvalidationProviderListXMLRequestBody() {
        }
        
        public GetInvalidationProviderListXMLRequestBody(System.Xml.Linq.XElement xmlElement) {
            this.xmlElement = xmlElement;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvalidationProviderListXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvalidationProviderListXMLResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListXMLResponseBody Body;
        
        public GetInvalidationProviderListXMLResponse() {
        }
        
        public GetInvalidationProviderListXMLResponse(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetInvalidationProviderListXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetInvalidationProviderListXMLResult;
        
        public GetInvalidationProviderListXMLResponseBody() {
        }
        
        public GetInvalidationProviderListXMLResponseBody(System.Xml.Linq.XElement GetInvalidationProviderListXMLResult) {
            this.GetInvalidationProviderListXMLResult = GetInvalidationProviderListXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvalidationProviderListSTRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvalidationProviderListSTR", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListSTRRequestBody Body;
        
        public GetInvalidationProviderListSTRRequest() {
        }
        
        public GetInvalidationProviderListSTRRequest(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListSTRRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetInvalidationProviderListSTRRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlDoc;
        
        public GetInvalidationProviderListSTRRequestBody() {
        }
        
        public GetInvalidationProviderListSTRRequestBody(string xmlDoc) {
            this.xmlDoc = xmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvalidationProviderListSTRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvalidationProviderListSTRResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListSTRResponseBody Body;
        
        public GetInvalidationProviderListSTRResponse() {
        }
        
        public GetInvalidationProviderListSTRResponse(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListSTRResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetInvalidationProviderListSTRResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInvalidationProviderListSTRResult;
        
        public GetInvalidationProviderListSTRResponseBody() {
        }
        
        public GetInvalidationProviderListSTRResponseBody(string GetInvalidationProviderListSTRResult) {
            this.GetInvalidationProviderListSTRResult = GetInvalidationProviderListSTRResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pnrCreateOrderExRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pnrCreateOrderEx", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExRequestBody Body;
        
        public pnrCreateOrderExRequest() {
        }
        
        public pnrCreateOrderExRequest(BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class pnrCreateOrderExRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement xeMessage;
        
        public pnrCreateOrderExRequestBody() {
        }
        
        public pnrCreateOrderExRequestBody(System.Xml.Linq.XElement xeMessage) {
            this.xeMessage = xeMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pnrCreateOrderExResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pnrCreateOrderExResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExResponseBody Body;
        
        public pnrCreateOrderExResponse() {
        }
        
        public pnrCreateOrderExResponse(BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class pnrCreateOrderExResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement pnrCreateOrderExResult;
        
        public pnrCreateOrderExResponseBody() {
        }
        
        public pnrCreateOrderExResponseBody(System.Xml.Linq.XElement pnrCreateOrderExResult) {
            this.pnrCreateOrderExResult = pnrCreateOrderExResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pnrCreateOrderExStrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pnrCreateOrderExStr", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExStrRequestBody Body;
        
        public pnrCreateOrderExStrRequest() {
        }
        
        public pnrCreateOrderExStrRequest(BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExStrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class pnrCreateOrderExStrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xeMessage;
        
        public pnrCreateOrderExStrRequestBody() {
        }
        
        public pnrCreateOrderExStrRequestBody(string xeMessage) {
            this.xeMessage = xeMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class pnrCreateOrderExStrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="pnrCreateOrderExStrResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExStrResponseBody Body;
        
        public pnrCreateOrderExStrResponse() {
        }
        
        public pnrCreateOrderExStrResponse(BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExStrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class pnrCreateOrderExStrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string pnrCreateOrderExStrResult;
        
        public pnrCreateOrderExStrResponseBody() {
        }
        
        public pnrCreateOrderExStrResponseBody(string pnrCreateOrderExStrResult) {
            this.pnrCreateOrderExStrResult = pnrCreateOrderExStrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrderInfo", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoRequestBody Body;
        
        public getOrderInfoRequest() {
        }
        
        public getOrderInfoRequest(BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class getOrderInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AgentCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string AgentUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AgentPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string OrderID;
        
        public getOrderInfoRequestBody() {
        }
        
        public getOrderInfoRequestBody(string AgentCode, string AgentUserName, string AgentPwd, string OrderID) {
            this.AgentCode = AgentCode;
            this.AgentUserName = AgentUserName;
            this.AgentPwd = AgentPwd;
            this.OrderID = OrderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrderInfoResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoResponseBody Body;
        
        public getOrderInfoResponse() {
        }
        
        public getOrderInfoResponse(BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class getOrderInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getOrderInfoResult;
        
        public getOrderInfoResponseBody() {
        }
        
        public getOrderInfoResponseBody(string getOrderInfoResult) {
            this.getOrderInfoResult = getOrderInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderInfoXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrderInfoXml", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoXmlRequestBody Body;
        
        public getOrderInfoXmlRequest() {
        }
        
        public getOrderInfoXmlRequest(BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class getOrderInfoXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement xmlMessage;
        
        public getOrderInfoXmlRequestBody() {
        }
        
        public getOrderInfoXmlRequestBody(System.Xml.Linq.XElement xmlMessage) {
            this.xmlMessage = xmlMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getOrderInfoXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getOrderInfoXmlResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoXmlResponseBody Body;
        
        public getOrderInfoXmlResponse() {
        }
        
        public getOrderInfoXmlResponse(BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class getOrderInfoXmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement getOrderInfoXmlResult;
        
        public getOrderInfoXmlResponseBody() {
        }
        
        public getOrderInfoXmlResponseBody(System.Xml.Linq.XElement getOrderInfoXmlResult) {
            this.getOrderInfoXmlResult = getOrderInfoXmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyXml", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyXmlRequestBody Body;
        
        public NotifyXmlRequest() {
        }
        
        public NotifyXmlRequest(BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class NotifyXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement XmlMessage;
        
        public NotifyXmlRequestBody() {
        }
        
        public NotifyXmlRequestBody(System.Xml.Linq.XElement XmlMessage) {
            this.XmlMessage = XmlMessage;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyXmlResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyXmlResponseBody Body;
        
        public NotifyXmlResponse() {
        }
        
        public NotifyXmlResponse(BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class NotifyXmlResponseBody {
        
        public NotifyXmlResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyStrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyStr", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyStrRequestBody Body;
        
        public NotifyStrRequest() {
        }
        
        public NotifyStrRequest(BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyStrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class NotifyStrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Message;
        
        public NotifyStrRequestBody() {
        }
        
        public NotifyStrRequestBody(string Message) {
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NotifyStrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NotifyStrResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyStrResponseBody Body;
        
        public NotifyStrResponse() {
        }
        
        public NotifyStrResponse(BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyStrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class NotifyStrResponseBody {
        
        public NotifyStrResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApplyRefundOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApplyRefundOrder", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderRequestBody Body;
        
        public ApplyRefundOrderRequest() {
        }
        
        public ApplyRefundOrderRequest(BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class ApplyRefundOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement xml;
        
        public ApplyRefundOrderRequestBody() {
        }
        
        public ApplyRefundOrderRequestBody(System.Xml.Linq.XElement xml) {
            this.xml = xml;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApplyRefundOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApplyRefundOrderResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderResponseBody Body;
        
        public ApplyRefundOrderResponse() {
        }
        
        public ApplyRefundOrderResponse(BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class ApplyRefundOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement ApplyRefundOrderResult;
        
        public ApplyRefundOrderResponseBody() {
        }
        
        public ApplyRefundOrderResponseBody(System.Xml.Linq.XElement ApplyRefundOrderResult) {
            this.ApplyRefundOrderResult = ApplyRefundOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApplyRefundOrderStrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApplyRefundOrderStr", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderStrRequestBody Body;
        
        public ApplyRefundOrderStrRequest() {
        }
        
        public ApplyRefundOrderStrRequest(BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderStrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class ApplyRefundOrderStrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Message;
        
        public ApplyRefundOrderStrRequestBody() {
        }
        
        public ApplyRefundOrderStrRequestBody(string Message) {
            this.Message = Message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApplyRefundOrderStrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApplyRefundOrderStrResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderStrResponseBody Body;
        
        public ApplyRefundOrderStrResponse() {
        }
        
        public ApplyRefundOrderStrResponse(BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderStrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class ApplyRefundOrderStrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ApplyRefundOrderStrResult;
        
        public ApplyRefundOrderStrResponseBody() {
        }
        
        public ApplyRefundOrderStrResponseBody(string ApplyRefundOrderStrResult) {
            this.ApplyRefundOrderStrResult = ApplyRefundOrderStrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUrlDataRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUrlData", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.GetUrlDataRequestBody Body;
        
        public GetUrlDataRequest() {
        }
        
        public GetUrlDataRequest(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetUrlDataRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetUrlDataRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        public GetUrlDataRequestBody() {
        }
        
        public GetUrlDataRequestBody(string url) {
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUrlDataResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUrlDataResponse", Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms.webbaituo.GetUrlDataResponseBody Body;
        
        public GetUrlDataResponse() {
        }
        
        public GetUrlDataResponse(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetUrlDataResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://203.88.210.234:114/BaiTuoWeb.asmx")]
    public partial class GetUrlDataResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetUrlDataResult;
        
        public GetUrlDataResponseBody() {
        }
        
        public GetUrlDataResponseBody(string GetUrlDataResult) {
            this.GetUrlDataResult = GetUrlDataResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BaiTuoWebSoapChannel : BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BaiTuoWebSoapClient : System.ServiceModel.ClientBase<BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap>, BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap {
        
        public BaiTuoWebSoapClient() {
        }
        
        public BaiTuoWebSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BaiTuoWebSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaiTuoWebSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaiTuoWebSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.GetAlterDomesticCabinZRateByParamResponse BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap.GetAlterDomesticCabinZRateByParam(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetAlterDomesticCabinZRateByParamRequest request) {
            return base.Channel.GetAlterDomesticCabinZRateByParam(request);
        }
        
        public System.Xml.Linq.XElement GetAlterDomesticCabinZRateByParam(string TripType, string TicketType, string CoAgentOffice, string CoUserName, string CoUserPwd, string RQStartDateTime) {
            BPiaoBao.DomesticTicket.Platforms.webbaituo.GetAlterDomesticCabinZRateByParamRequest inValue = new BPiaoBao.DomesticTicket.Platforms.webbaituo.GetAlterDomesticCabinZRateByParamRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms.webbaituo.GetAlterDomesticCabinZRateByParamRequestBody();
            inValue.Body.TripType = TripType;
            inValue.Body.TicketType = TicketType;
            inValue.Body.CoAgentOffice = CoAgentOffice;
            inValue.Body.CoUserName = CoUserName;
            inValue.Body.CoUserPwd = CoUserPwd;
            inValue.Body.RQStartDateTime = RQStartDateTime;
            BPiaoBao.DomesticTicket.Platforms.webbaituo.GetAlterDomesticCabinZRateByParamResponse retVal = ((BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap)(this)).GetAlterDomesticCabinZRateByParam(inValue);
            return retVal.Body.GetAlterDomesticCabinZRateByParamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateListResponse BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap.GetDomesticMatchNormalZRateList(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateListRequest request) {
            return base.Channel.GetDomesticMatchNormalZRateList(request);
        }
        
        public System.Xml.Linq.XElement GetDomesticMatchNormalZRateList(System.Xml.Linq.XElement xmlMessage) {
            BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateListRequest inValue = new BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateListRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateListRequestBody();
            inValue.Body.xmlMessage = xmlMessage;
            BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateListResponse retVal = ((BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap)(this)).GetDomesticMatchNormalZRateList(inValue);
            return retVal.Body.GetDomesticMatchNormalZRateListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateStrResponse BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap.GetDomesticMatchNormalZRateStr(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateStrRequest request) {
            return base.Channel.GetDomesticMatchNormalZRateStr(request);
        }
        
        public string GetDomesticMatchNormalZRateStr(string xmlMessage) {
            BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateStrRequest inValue = new BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateStrRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateStrRequestBody();
            inValue.Body.xmlMessage = xmlMessage;
            BPiaoBao.DomesticTicket.Platforms.webbaituo.GetDomesticMatchNormalZRateStrResponse retVal = ((BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap)(this)).GetDomesticMatchNormalZRateStr(inValue);
            return retVal.Body.GetDomesticMatchNormalZRateStrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListXMLResponse BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap.GetInvalidationProviderListXML(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListXMLRequest request) {
            return base.Channel.GetInvalidationProviderListXML(request);
        }
        
        public System.Xml.Linq.XElement GetInvalidationProviderListXML(System.Xml.Linq.XElement xmlElement) {
            BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListXMLRequest inValue = new BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListXMLRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListXMLRequestBody();
            inValue.Body.xmlElement = xmlElement;
            BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListXMLResponse retVal = ((BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap)(this)).GetInvalidationProviderListXML(inValue);
            return retVal.Body.GetInvalidationProviderListXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListSTRResponse BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap.GetInvalidationProviderListSTR(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListSTRRequest request) {
            return base.Channel.GetInvalidationProviderListSTR(request);
        }
        
        public string GetInvalidationProviderListSTR(string xmlDoc) {
            BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListSTRRequest inValue = new BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListSTRRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListSTRRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            BPiaoBao.DomesticTicket.Platforms.webbaituo.GetInvalidationProviderListSTRResponse retVal = ((BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap)(this)).GetInvalidationProviderListSTR(inValue);
            return retVal.Body.GetInvalidationProviderListSTRResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExResponse BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap.pnrCreateOrderEx(BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExRequest request) {
            return base.Channel.pnrCreateOrderEx(request);
        }
        
        public System.Xml.Linq.XElement pnrCreateOrderEx(System.Xml.Linq.XElement xeMessage) {
            BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExRequest inValue = new BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExRequestBody();
            inValue.Body.xeMessage = xeMessage;
            BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExResponse retVal = ((BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap)(this)).pnrCreateOrderEx(inValue);
            return retVal.Body.pnrCreateOrderExResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExStrResponse BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap.pnrCreateOrderExStr(BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExStrRequest request) {
            return base.Channel.pnrCreateOrderExStr(request);
        }
        
        public string pnrCreateOrderExStr(string xeMessage) {
            BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExStrRequest inValue = new BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExStrRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExStrRequestBody();
            inValue.Body.xeMessage = xeMessage;
            BPiaoBao.DomesticTicket.Platforms.webbaituo.pnrCreateOrderExStrResponse retVal = ((BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap)(this)).pnrCreateOrderExStr(inValue);
            return retVal.Body.pnrCreateOrderExStrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoResponse BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap.getOrderInfo(BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoRequest request) {
            return base.Channel.getOrderInfo(request);
        }
        
        public string getOrderInfo(string AgentCode, string AgentUserName, string AgentPwd, string OrderID) {
            BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoRequest inValue = new BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoRequestBody();
            inValue.Body.AgentCode = AgentCode;
            inValue.Body.AgentUserName = AgentUserName;
            inValue.Body.AgentPwd = AgentPwd;
            inValue.Body.OrderID = OrderID;
            BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoResponse retVal = ((BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap)(this)).getOrderInfo(inValue);
            return retVal.Body.getOrderInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoXmlResponse BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap.getOrderInfoXml(BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoXmlRequest request) {
            return base.Channel.getOrderInfoXml(request);
        }
        
        public System.Xml.Linq.XElement getOrderInfoXml(System.Xml.Linq.XElement xmlMessage) {
            BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoXmlRequest inValue = new BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoXmlRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoXmlRequestBody();
            inValue.Body.xmlMessage = xmlMessage;
            BPiaoBao.DomesticTicket.Platforms.webbaituo.getOrderInfoXmlResponse retVal = ((BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap)(this)).getOrderInfoXml(inValue);
            return retVal.Body.getOrderInfoXmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyXmlResponse BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap.NotifyXml(BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyXmlRequest request) {
            return base.Channel.NotifyXml(request);
        }
        
        public void NotifyXml(System.Xml.Linq.XElement XmlMessage) {
            BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyXmlRequest inValue = new BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyXmlRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyXmlRequestBody();
            inValue.Body.XmlMessage = XmlMessage;
            BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyXmlResponse retVal = ((BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap)(this)).NotifyXml(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyStrResponse BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap.NotifyStr(BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyStrRequest request) {
            return base.Channel.NotifyStr(request);
        }
        
        public void NotifyStr(string Message) {
            BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyStrRequest inValue = new BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyStrRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyStrRequestBody();
            inValue.Body.Message = Message;
            BPiaoBao.DomesticTicket.Platforms.webbaituo.NotifyStrResponse retVal = ((BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap)(this)).NotifyStr(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderResponse BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap.ApplyRefundOrder(BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderRequest request) {
            return base.Channel.ApplyRefundOrder(request);
        }
        
        public System.Xml.Linq.XElement ApplyRefundOrder(System.Xml.Linq.XElement xml) {
            BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderRequest inValue = new BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderRequestBody();
            inValue.Body.xml = xml;
            BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderResponse retVal = ((BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap)(this)).ApplyRefundOrder(inValue);
            return retVal.Body.ApplyRefundOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderStrResponse BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap.ApplyRefundOrderStr(BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderStrRequest request) {
            return base.Channel.ApplyRefundOrderStr(request);
        }
        
        public string ApplyRefundOrderStr(string Message) {
            BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderStrRequest inValue = new BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderStrRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderStrRequestBody();
            inValue.Body.Message = Message;
            BPiaoBao.DomesticTicket.Platforms.webbaituo.ApplyRefundOrderStrResponse retVal = ((BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap)(this)).ApplyRefundOrderStr(inValue);
            return retVal.Body.ApplyRefundOrderStrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms.webbaituo.GetUrlDataResponse BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap.GetUrlData(BPiaoBao.DomesticTicket.Platforms.webbaituo.GetUrlDataRequest request) {
            return base.Channel.GetUrlData(request);
        }
        
        public string GetUrlData(string url) {
            BPiaoBao.DomesticTicket.Platforms.webbaituo.GetUrlDataRequest inValue = new BPiaoBao.DomesticTicket.Platforms.webbaituo.GetUrlDataRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms.webbaituo.GetUrlDataRequestBody();
            inValue.Body.url = url;
            BPiaoBao.DomesticTicket.Platforms.webbaituo.GetUrlDataResponse retVal = ((BPiaoBao.DomesticTicket.Platforms.webbaituo.BaiTuoWebSoap)(this)).GetUrlData(inValue);
            return retVal.Body.GetUrlDataResult;
        }
    }
}
