//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.19075
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.baitour.com/", ConfigurationName="_baiTuoPolicy.AirWsCoManageSoap")]
    public interface AirWsCoManageSoap {
        
        // CODEGEN: 命名空间 http://www.baitour.com/ 的元素名称 TripType 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/GetAlterDomesticCabinZRateByParam", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByParamResponse GetAlterDomesticCabinZRateByParam(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByParamRequest request);
        
        // CODEGEN: 命名空间 http://www.baitour.com/ 的元素名称 xmlDoc 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/GetAlterDomesticCabinZRateByXml", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByXmlResponse GetAlterDomesticCabinZRateByXml(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByXmlRequest request);
        
        // CODEGEN: 命名空间 http://www.baitour.com/ 的元素名称 xmlDoc 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/GetDomesticMatchNormalZRate", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateResponse GetDomesticMatchNormalZRate(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateRequest request);
        
        // CODEGEN: 命名空间 http://www.baitour.com/ 的元素名称 xmlDoc 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/GetDomesticMatchNormalZRateStr", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateStrResponse GetDomesticMatchNormalZRateStr(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateStrRequest request);
        
        // CODEGEN: 命名空间 http://www.baitour.com/ 的元素名称 GetInvalidationProviderOfficeNoListResult 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/GetInvalidationProviderOfficeNoList", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderOfficeNoListResponse GetInvalidationProviderOfficeNoList(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderOfficeNoListRequest request);
        
        // CODEGEN: 命名空间 http://www.baitour.com/ 的元素名称 CoUserName 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/GetInvalidationProviderList", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListResponse GetInvalidationProviderList(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListRequest request);
        
        // CODEGEN: 命名空间 http://www.baitour.com/ 的元素名称 xmlDoc 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/GetInvalidationProviderListXML", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListXMLResponse GetInvalidationProviderListXML(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListXMLRequest request);
        
        // CODEGEN: 命名空间 http://www.baitour.com/ 的元素名称 xmlDoc 以后生成的消息协定未标记为 nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/GetInvalidationProviderListSTR", ReplyAction="*")]
        BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListSTRResponse GetInvalidationProviderListSTR(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListSTRRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlterDomesticCabinZRateByParamRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlterDomesticCabinZRateByParam", Namespace="http://www.baitour.com/", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByParamRequestBody Body;
        
        public GetAlterDomesticCabinZRateByParamRequest() {
        }
        
        public GetAlterDomesticCabinZRateByParamRequest(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByParamRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baitour.com/")]
    public partial class GetAlterDomesticCabinZRateByParamRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TripType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ProviderOfficeId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string TicketType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string CoServerName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string CoAgentOffice;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string CoUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string CoPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string RQType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string RQDateTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string IntervalTime;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string RQStartDateTime;
        
        public GetAlterDomesticCabinZRateByParamRequestBody() {
        }
        
        public GetAlterDomesticCabinZRateByParamRequestBody(string TripType, string ProviderOfficeId, string TicketType, string CoServerName, string CoAgentOffice, string CoUserName, string CoPwd, string RQType, string RQDateTime, string IntervalTime, string RQStartDateTime) {
            this.TripType = TripType;
            this.ProviderOfficeId = ProviderOfficeId;
            this.TicketType = TicketType;
            this.CoServerName = CoServerName;
            this.CoAgentOffice = CoAgentOffice;
            this.CoUserName = CoUserName;
            this.CoPwd = CoPwd;
            this.RQType = RQType;
            this.RQDateTime = RQDateTime;
            this.IntervalTime = IntervalTime;
            this.RQStartDateTime = RQStartDateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlterDomesticCabinZRateByParamResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlterDomesticCabinZRateByParamResponse", Namespace="http://www.baitour.com/", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByParamResponseBody Body;
        
        public GetAlterDomesticCabinZRateByParamResponse() {
        }
        
        public GetAlterDomesticCabinZRateByParamResponse(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByParamResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baitour.com/")]
    public partial class GetAlterDomesticCabinZRateByParamResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetAlterDomesticCabinZRateByParamResult;
        
        public GetAlterDomesticCabinZRateByParamResponseBody() {
        }
        
        public GetAlterDomesticCabinZRateByParamResponseBody(System.Xml.Linq.XElement GetAlterDomesticCabinZRateByParamResult) {
            this.GetAlterDomesticCabinZRateByParamResult = GetAlterDomesticCabinZRateByParamResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlterDomesticCabinZRateByXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlterDomesticCabinZRateByXml", Namespace="http://www.baitour.com/", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByXmlRequestBody Body;
        
        public GetAlterDomesticCabinZRateByXmlRequest() {
        }
        
        public GetAlterDomesticCabinZRateByXmlRequest(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baitour.com/")]
    public partial class GetAlterDomesticCabinZRateByXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement xmlDoc;
        
        public GetAlterDomesticCabinZRateByXmlRequestBody() {
        }
        
        public GetAlterDomesticCabinZRateByXmlRequestBody(System.Xml.Linq.XElement xmlDoc) {
            this.xmlDoc = xmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlterDomesticCabinZRateByXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlterDomesticCabinZRateByXmlResponse", Namespace="http://www.baitour.com/", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByXmlResponseBody Body;
        
        public GetAlterDomesticCabinZRateByXmlResponse() {
        }
        
        public GetAlterDomesticCabinZRateByXmlResponse(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baitour.com/")]
    public partial class GetAlterDomesticCabinZRateByXmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetAlterDomesticCabinZRateByXmlResult;
        
        public GetAlterDomesticCabinZRateByXmlResponseBody() {
        }
        
        public GetAlterDomesticCabinZRateByXmlResponseBody(System.Xml.Linq.XElement GetAlterDomesticCabinZRateByXmlResult) {
            this.GetAlterDomesticCabinZRateByXmlResult = GetAlterDomesticCabinZRateByXmlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomesticMatchNormalZRateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomesticMatchNormalZRate", Namespace="http://www.baitour.com/", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateRequestBody Body;
        
        public GetDomesticMatchNormalZRateRequest() {
        }
        
        public GetDomesticMatchNormalZRateRequest(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baitour.com/")]
    public partial class GetDomesticMatchNormalZRateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement xmlDoc;
        
        public GetDomesticMatchNormalZRateRequestBody() {
        }
        
        public GetDomesticMatchNormalZRateRequestBody(System.Xml.Linq.XElement xmlDoc) {
            this.xmlDoc = xmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomesticMatchNormalZRateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomesticMatchNormalZRateResponse", Namespace="http://www.baitour.com/", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateResponseBody Body;
        
        public GetDomesticMatchNormalZRateResponse() {
        }
        
        public GetDomesticMatchNormalZRateResponse(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baitour.com/")]
    public partial class GetDomesticMatchNormalZRateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetDomesticMatchNormalZRateResult;
        
        public GetDomesticMatchNormalZRateResponseBody() {
        }
        
        public GetDomesticMatchNormalZRateResponseBody(System.Xml.Linq.XElement GetDomesticMatchNormalZRateResult) {
            this.GetDomesticMatchNormalZRateResult = GetDomesticMatchNormalZRateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomesticMatchNormalZRateStrRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomesticMatchNormalZRateStr", Namespace="http://www.baitour.com/", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateStrRequestBody Body;
        
        public GetDomesticMatchNormalZRateStrRequest() {
        }
        
        public GetDomesticMatchNormalZRateStrRequest(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateStrRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baitour.com/")]
    public partial class GetDomesticMatchNormalZRateStrRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlDoc;
        
        public GetDomesticMatchNormalZRateStrRequestBody() {
        }
        
        public GetDomesticMatchNormalZRateStrRequestBody(string xmlDoc) {
            this.xmlDoc = xmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDomesticMatchNormalZRateStrResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDomesticMatchNormalZRateStrResponse", Namespace="http://www.baitour.com/", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateStrResponseBody Body;
        
        public GetDomesticMatchNormalZRateStrResponse() {
        }
        
        public GetDomesticMatchNormalZRateStrResponse(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateStrResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baitour.com/")]
    public partial class GetDomesticMatchNormalZRateStrResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDomesticMatchNormalZRateStrResult;
        
        public GetDomesticMatchNormalZRateStrResponseBody() {
        }
        
        public GetDomesticMatchNormalZRateStrResponseBody(string GetDomesticMatchNormalZRateStrResult) {
            this.GetDomesticMatchNormalZRateStrResult = GetDomesticMatchNormalZRateStrResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvalidationProviderOfficeNoListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvalidationProviderOfficeNoList", Namespace="http://www.baitour.com/", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderOfficeNoListRequestBody Body;
        
        public GetInvalidationProviderOfficeNoListRequest() {
        }
        
        public GetInvalidationProviderOfficeNoListRequest(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderOfficeNoListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetInvalidationProviderOfficeNoListRequestBody {
        
        public GetInvalidationProviderOfficeNoListRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvalidationProviderOfficeNoListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvalidationProviderOfficeNoListResponse", Namespace="http://www.baitour.com/", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderOfficeNoListResponseBody Body;
        
        public GetInvalidationProviderOfficeNoListResponse() {
        }
        
        public GetInvalidationProviderOfficeNoListResponse(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderOfficeNoListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baitour.com/")]
    public partial class GetInvalidationProviderOfficeNoListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInvalidationProviderOfficeNoListResult;
        
        public GetInvalidationProviderOfficeNoListResponseBody() {
        }
        
        public GetInvalidationProviderOfficeNoListResponseBody(string GetInvalidationProviderOfficeNoListResult) {
            this.GetInvalidationProviderOfficeNoListResult = GetInvalidationProviderOfficeNoListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvalidationProviderListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvalidationProviderList", Namespace="http://www.baitour.com/", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListRequestBody Body;
        
        public GetInvalidationProviderListRequest() {
        }
        
        public GetInvalidationProviderListRequest(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baitour.com/")]
    public partial class GetInvalidationProviderListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CoUserName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CoPwd;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string AgentCode;
        
        public GetInvalidationProviderListRequestBody() {
        }
        
        public GetInvalidationProviderListRequestBody(string CoUserName, string CoPwd, string AgentCode) {
            this.CoUserName = CoUserName;
            this.CoPwd = CoPwd;
            this.AgentCode = AgentCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvalidationProviderListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvalidationProviderListResponse", Namespace="http://www.baitour.com/", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListResponseBody Body;
        
        public GetInvalidationProviderListResponse() {
        }
        
        public GetInvalidationProviderListResponse(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baitour.com/")]
    public partial class GetInvalidationProviderListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInvalidationProviderListResult;
        
        public GetInvalidationProviderListResponseBody() {
        }
        
        public GetInvalidationProviderListResponseBody(string GetInvalidationProviderListResult) {
            this.GetInvalidationProviderListResult = GetInvalidationProviderListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvalidationProviderListXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvalidationProviderListXML", Namespace="http://www.baitour.com/", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListXMLRequestBody Body;
        
        public GetInvalidationProviderListXMLRequest() {
        }
        
        public GetInvalidationProviderListXMLRequest(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListXMLRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baitour.com/")]
    public partial class GetInvalidationProviderListXMLRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement xmlDoc;
        
        public GetInvalidationProviderListXMLRequestBody() {
        }
        
        public GetInvalidationProviderListXMLRequestBody(System.Xml.Linq.XElement xmlDoc) {
            this.xmlDoc = xmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvalidationProviderListXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvalidationProviderListXMLResponse", Namespace="http://www.baitour.com/", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListXMLResponseBody Body;
        
        public GetInvalidationProviderListXMLResponse() {
        }
        
        public GetInvalidationProviderListXMLResponse(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListXMLResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baitour.com/")]
    public partial class GetInvalidationProviderListXMLResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Xml.Linq.XElement GetInvalidationProviderListXMLResult;
        
        public GetInvalidationProviderListXMLResponseBody() {
        }
        
        public GetInvalidationProviderListXMLResponseBody(System.Xml.Linq.XElement GetInvalidationProviderListXMLResult) {
            this.GetInvalidationProviderListXMLResult = GetInvalidationProviderListXMLResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvalidationProviderListSTRRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvalidationProviderListSTR", Namespace="http://www.baitour.com/", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListSTRRequestBody Body;
        
        public GetInvalidationProviderListSTRRequest() {
        }
        
        public GetInvalidationProviderListSTRRequest(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListSTRRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baitour.com/")]
    public partial class GetInvalidationProviderListSTRRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string xmlDoc;
        
        public GetInvalidationProviderListSTRRequestBody() {
        }
        
        public GetInvalidationProviderListSTRRequestBody(string xmlDoc) {
            this.xmlDoc = xmlDoc;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetInvalidationProviderListSTRResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInvalidationProviderListSTRResponse", Namespace="http://www.baitour.com/", Order=0)]
        public BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListSTRResponseBody Body;
        
        public GetInvalidationProviderListSTRResponse() {
        }
        
        public GetInvalidationProviderListSTRResponse(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListSTRResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.baitour.com/")]
    public partial class GetInvalidationProviderListSTRResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetInvalidationProviderListSTRResult;
        
        public GetInvalidationProviderListSTRResponseBody() {
        }
        
        public GetInvalidationProviderListSTRResponseBody(string GetInvalidationProviderListSTRResult) {
            this.GetInvalidationProviderListSTRResult = GetInvalidationProviderListSTRResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AirWsCoManageSoapChannel : BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.AirWsCoManageSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AirWsCoManageSoapClient : System.ServiceModel.ClientBase<BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.AirWsCoManageSoap>, BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.AirWsCoManageSoap {
        
        public AirWsCoManageSoapClient() {
        }
        
        public AirWsCoManageSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AirWsCoManageSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AirWsCoManageSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AirWsCoManageSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByParamResponse BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.AirWsCoManageSoap.GetAlterDomesticCabinZRateByParam(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByParamRequest request) {
            return base.Channel.GetAlterDomesticCabinZRateByParam(request);
        }
        
        public System.Xml.Linq.XElement GetAlterDomesticCabinZRateByParam(string TripType, string ProviderOfficeId, string TicketType, string CoServerName, string CoAgentOffice, string CoUserName, string CoPwd, string RQType, string RQDateTime, string IntervalTime, string RQStartDateTime) {
            BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByParamRequest inValue = new BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByParamRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByParamRequestBody();
            inValue.Body.TripType = TripType;
            inValue.Body.ProviderOfficeId = ProviderOfficeId;
            inValue.Body.TicketType = TicketType;
            inValue.Body.CoServerName = CoServerName;
            inValue.Body.CoAgentOffice = CoAgentOffice;
            inValue.Body.CoUserName = CoUserName;
            inValue.Body.CoPwd = CoPwd;
            inValue.Body.RQType = RQType;
            inValue.Body.RQDateTime = RQDateTime;
            inValue.Body.IntervalTime = IntervalTime;
            inValue.Body.RQStartDateTime = RQStartDateTime;
            BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByParamResponse retVal = ((BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.AirWsCoManageSoap)(this)).GetAlterDomesticCabinZRateByParam(inValue);
            return retVal.Body.GetAlterDomesticCabinZRateByParamResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByXmlResponse BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.AirWsCoManageSoap.GetAlterDomesticCabinZRateByXml(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByXmlRequest request) {
            return base.Channel.GetAlterDomesticCabinZRateByXml(request);
        }
        
        public System.Xml.Linq.XElement GetAlterDomesticCabinZRateByXml(System.Xml.Linq.XElement xmlDoc) {
            BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByXmlRequest inValue = new BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByXmlRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByXmlRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetAlterDomesticCabinZRateByXmlResponse retVal = ((BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.AirWsCoManageSoap)(this)).GetAlterDomesticCabinZRateByXml(inValue);
            return retVal.Body.GetAlterDomesticCabinZRateByXmlResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateResponse BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.AirWsCoManageSoap.GetDomesticMatchNormalZRate(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateRequest request) {
            return base.Channel.GetDomesticMatchNormalZRate(request);
        }
        
        public System.Xml.Linq.XElement GetDomesticMatchNormalZRate(System.Xml.Linq.XElement xmlDoc) {
            BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateRequest inValue = new BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateResponse retVal = ((BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.AirWsCoManageSoap)(this)).GetDomesticMatchNormalZRate(inValue);
            return retVal.Body.GetDomesticMatchNormalZRateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateStrResponse BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.AirWsCoManageSoap.GetDomesticMatchNormalZRateStr(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateStrRequest request) {
            return base.Channel.GetDomesticMatchNormalZRateStr(request);
        }
        
        public string GetDomesticMatchNormalZRateStr(string xmlDoc) {
            BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateStrRequest inValue = new BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateStrRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateStrRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetDomesticMatchNormalZRateStrResponse retVal = ((BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.AirWsCoManageSoap)(this)).GetDomesticMatchNormalZRateStr(inValue);
            return retVal.Body.GetDomesticMatchNormalZRateStrResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderOfficeNoListResponse BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.AirWsCoManageSoap.GetInvalidationProviderOfficeNoList(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderOfficeNoListRequest request) {
            return base.Channel.GetInvalidationProviderOfficeNoList(request);
        }
        
        public string GetInvalidationProviderOfficeNoList() {
            BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderOfficeNoListRequest inValue = new BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderOfficeNoListRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderOfficeNoListRequestBody();
            BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderOfficeNoListResponse retVal = ((BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.AirWsCoManageSoap)(this)).GetInvalidationProviderOfficeNoList(inValue);
            return retVal.Body.GetInvalidationProviderOfficeNoListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListResponse BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.AirWsCoManageSoap.GetInvalidationProviderList(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListRequest request) {
            return base.Channel.GetInvalidationProviderList(request);
        }
        
        public string GetInvalidationProviderList(string CoUserName, string CoPwd, string AgentCode) {
            BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListRequest inValue = new BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListRequestBody();
            inValue.Body.CoUserName = CoUserName;
            inValue.Body.CoPwd = CoPwd;
            inValue.Body.AgentCode = AgentCode;
            BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListResponse retVal = ((BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.AirWsCoManageSoap)(this)).GetInvalidationProviderList(inValue);
            return retVal.Body.GetInvalidationProviderListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListXMLResponse BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.AirWsCoManageSoap.GetInvalidationProviderListXML(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListXMLRequest request) {
            return base.Channel.GetInvalidationProviderListXML(request);
        }
        
        public System.Xml.Linq.XElement GetInvalidationProviderListXML(System.Xml.Linq.XElement xmlDoc) {
            BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListXMLRequest inValue = new BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListXMLRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListXMLRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListXMLResponse retVal = ((BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.AirWsCoManageSoap)(this)).GetInvalidationProviderListXML(inValue);
            return retVal.Body.GetInvalidationProviderListXMLResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListSTRResponse BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.AirWsCoManageSoap.GetInvalidationProviderListSTR(BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListSTRRequest request) {
            return base.Channel.GetInvalidationProviderListSTR(request);
        }
        
        public string GetInvalidationProviderListSTR(string xmlDoc) {
            BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListSTRRequest inValue = new BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListSTRRequest();
            inValue.Body = new BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListSTRRequestBody();
            inValue.Body.xmlDoc = xmlDoc;
            BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.GetInvalidationProviderListSTRResponse retVal = ((BPiaoBao.DomesticTicket.Platforms._baiTuoPolicy.AirWsCoManageSoap)(this)).GetInvalidationProviderListSTR(inValue);
            return retVal.Body.GetInvalidationProviderListSTRResult;
        }
    }
}
