//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPiaoBao.DomesticTicket.Domain.IBEService {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://210.14.138.30/", ConfigurationName="IBEService.WebService1Soap")]
    public interface WebService1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://210.14.138.30/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://210.14.138.30/getIBEAVData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string getIBEAVData(string FromCity, string ToCity, string FlightDate, string FlightTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://210.14.138.30/getIBEFDData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getIBEFDData(string FromCity, string ToCity, string FlightDate, string FlightTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://210.14.138.30/getIBEFDDataTest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getIBEFDDataTest(string FromCity, string ToCity, string FlightDate, string FlightTime);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : BPiaoBao.DomesticTicket.Domain.IBEService.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<BPiaoBao.DomesticTicket.Domain.IBEService.WebService1Soap>, BPiaoBao.DomesticTicket.Domain.IBEService.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public string getIBEAVData(string FromCity, string ToCity, string FlightDate, string FlightTime) {
            return base.Channel.getIBEAVData(FromCity, ToCity, FlightDate, FlightTime);
        }
        
        public System.Data.DataSet getIBEFDData(string FromCity, string ToCity, string FlightDate, string FlightTime) {
            return base.Channel.getIBEFDData(FromCity, ToCity, FlightDate, FlightTime);
        }
        
        public System.Data.DataSet getIBEFDDataTest(string FromCity, string ToCity, string FlightDate, string FlightTime) {
            return base.Channel.getIBEFDDataTest(FromCity, ToCity, FlightDate, FlightTime);
        }
    }
}
