//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPiaoBao.DomesticTicket.Platforms._baiTuo {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.baitour.com/", ConfigurationName="_baiTuo.BaitourServiceSoap")]
    public interface BaitourServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/GetAllCommonPolicy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAllCommonPolicy(string tripType, string ticketType, string agentUserName, string pwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/GetAllCommonPolicyZIP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAllCommonPolicyZIP(string tripType, string ticketType, string agentUserName, string pwd, string zip);
        
        // CODEGEN: 参数“GetAllCommonFileStreamPolicyZIPResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/GetAllCommonFileStreamPolicyZIP", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BPiaoBao.DomesticTicket.Platforms._baiTuo.GetAllCommonFileStreamPolicyZIPResponse GetAllCommonFileStreamPolicyZIP(BPiaoBao.DomesticTicket.Platforms._baiTuo.GetAllCommonFileStreamPolicyZIPRequest request);
        
        // CODEGEN: 参数“GetAlterCommonFileStreamPolicyResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/GetAlterCommonFileStreamPolicy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        BPiaoBao.DomesticTicket.Platforms._baiTuo.GetAlterCommonFileStreamPolicyResponse GetAlterCommonFileStreamPolicy(BPiaoBao.DomesticTicket.Platforms._baiTuo.GetAlterCommonFileStreamPolicyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/GetAlterCommonPolicy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAlterCommonPolicy(string tripType, string ticketType, string agentUserName, string pwd, string rQStartDateTime);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/MatchCommonPolicy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MatchCommonPolicy(string xmlDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/MatchCommonPolicyNew", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MatchCommonPolicyNew(string xmlDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/GetAVPolicy", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAVPolicy(string xmlDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/GetDomesticMatchNormalZRateByID", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetDomesticMatchNormalZRateByID(string xmlDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/DetailCreateOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string DetailCreateOrder(string xmlDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/RTCreateOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RTCreateOrder(string xmlDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/ChdDetailCreateOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Xml.XmlNode ChdDetailCreateOrder(string xmlDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/GetOrderInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetOrderInfo(string AgentCode, string AgentUserName, string AgentPwd, string OrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/GetInvalidationProviders", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetInvalidationProviders(string AgentCode, string AgentUserName, string AgentPwd);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/RefundOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string RefundOrder(string xmlDoc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.baitour.com/GetChangeFlightDate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetChangeFlightDate(string xmlDoc);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllCommonFileStreamPolicyZIP", WrapperNamespace="http://www.baitour.com/", IsWrapped=true)]
    public partial class GetAllCommonFileStreamPolicyZIPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.baitour.com/", Order=0)]
        public string tripType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.baitour.com/", Order=1)]
        public string ticketType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.baitour.com/", Order=2)]
        public string agentUserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.baitour.com/", Order=3)]
        public string pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.baitour.com/", Order=4)]
        public string zip;
        
        public GetAllCommonFileStreamPolicyZIPRequest() {
        }
        
        public GetAllCommonFileStreamPolicyZIPRequest(string tripType, string ticketType, string agentUserName, string pwd, string zip) {
            this.tripType = tripType;
            this.ticketType = ticketType;
            this.agentUserName = agentUserName;
            this.pwd = pwd;
            this.zip = zip;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAllCommonFileStreamPolicyZIPResponse", WrapperNamespace="http://www.baitour.com/", IsWrapped=true)]
    public partial class GetAllCommonFileStreamPolicyZIPResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.baitour.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetAllCommonFileStreamPolicyZIPResult;
        
        public GetAllCommonFileStreamPolicyZIPResponse() {
        }
        
        public GetAllCommonFileStreamPolicyZIPResponse(byte[] GetAllCommonFileStreamPolicyZIPResult) {
            this.GetAllCommonFileStreamPolicyZIPResult = GetAllCommonFileStreamPolicyZIPResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAlterCommonFileStreamPolicy", WrapperNamespace="http://www.baitour.com/", IsWrapped=true)]
    public partial class GetAlterCommonFileStreamPolicyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.baitour.com/", Order=0)]
        public string tripType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.baitour.com/", Order=1)]
        public string ticketType;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.baitour.com/", Order=2)]
        public string agentUserName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.baitour.com/", Order=3)]
        public string pwd;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.baitour.com/", Order=4)]
        public string rQStartDateTime;
        
        public GetAlterCommonFileStreamPolicyRequest() {
        }
        
        public GetAlterCommonFileStreamPolicyRequest(string tripType, string ticketType, string agentUserName, string pwd, string rQStartDateTime) {
            this.tripType = tripType;
            this.ticketType = ticketType;
            this.agentUserName = agentUserName;
            this.pwd = pwd;
            this.rQStartDateTime = rQStartDateTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAlterCommonFileStreamPolicyResponse", WrapperNamespace="http://www.baitour.com/", IsWrapped=true)]
    public partial class GetAlterCommonFileStreamPolicyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.baitour.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetAlterCommonFileStreamPolicyResult;
        
        public GetAlterCommonFileStreamPolicyResponse() {
        }
        
        public GetAlterCommonFileStreamPolicyResponse(byte[] GetAlterCommonFileStreamPolicyResult) {
            this.GetAlterCommonFileStreamPolicyResult = GetAlterCommonFileStreamPolicyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BaitourServiceSoapChannel : BPiaoBao.DomesticTicket.Platforms._baiTuo.BaitourServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BaitourServiceSoapClient : System.ServiceModel.ClientBase<BPiaoBao.DomesticTicket.Platforms._baiTuo.BaitourServiceSoap>, BPiaoBao.DomesticTicket.Platforms._baiTuo.BaitourServiceSoap {
        
        public BaitourServiceSoapClient() {
        }
        
        public BaitourServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BaitourServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaitourServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BaitourServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetAllCommonPolicy(string tripType, string ticketType, string agentUserName, string pwd) {
            return base.Channel.GetAllCommonPolicy(tripType, ticketType, agentUserName, pwd);
        }
        
        public string GetAllCommonPolicyZIP(string tripType, string ticketType, string agentUserName, string pwd, string zip) {
            return base.Channel.GetAllCommonPolicyZIP(tripType, ticketType, agentUserName, pwd, zip);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms._baiTuo.GetAllCommonFileStreamPolicyZIPResponse BPiaoBao.DomesticTicket.Platforms._baiTuo.BaitourServiceSoap.GetAllCommonFileStreamPolicyZIP(BPiaoBao.DomesticTicket.Platforms._baiTuo.GetAllCommonFileStreamPolicyZIPRequest request) {
            return base.Channel.GetAllCommonFileStreamPolicyZIP(request);
        }
        
        public byte[] GetAllCommonFileStreamPolicyZIP(string tripType, string ticketType, string agentUserName, string pwd, string zip) {
            BPiaoBao.DomesticTicket.Platforms._baiTuo.GetAllCommonFileStreamPolicyZIPRequest inValue = new BPiaoBao.DomesticTicket.Platforms._baiTuo.GetAllCommonFileStreamPolicyZIPRequest();
            inValue.tripType = tripType;
            inValue.ticketType = ticketType;
            inValue.agentUserName = agentUserName;
            inValue.pwd = pwd;
            inValue.zip = zip;
            BPiaoBao.DomesticTicket.Platforms._baiTuo.GetAllCommonFileStreamPolicyZIPResponse retVal = ((BPiaoBao.DomesticTicket.Platforms._baiTuo.BaitourServiceSoap)(this)).GetAllCommonFileStreamPolicyZIP(inValue);
            return retVal.GetAllCommonFileStreamPolicyZIPResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        BPiaoBao.DomesticTicket.Platforms._baiTuo.GetAlterCommonFileStreamPolicyResponse BPiaoBao.DomesticTicket.Platforms._baiTuo.BaitourServiceSoap.GetAlterCommonFileStreamPolicy(BPiaoBao.DomesticTicket.Platforms._baiTuo.GetAlterCommonFileStreamPolicyRequest request) {
            return base.Channel.GetAlterCommonFileStreamPolicy(request);
        }
        
        public byte[] GetAlterCommonFileStreamPolicy(string tripType, string ticketType, string agentUserName, string pwd, string rQStartDateTime) {
            BPiaoBao.DomesticTicket.Platforms._baiTuo.GetAlterCommonFileStreamPolicyRequest inValue = new BPiaoBao.DomesticTicket.Platforms._baiTuo.GetAlterCommonFileStreamPolicyRequest();
            inValue.tripType = tripType;
            inValue.ticketType = ticketType;
            inValue.agentUserName = agentUserName;
            inValue.pwd = pwd;
            inValue.rQStartDateTime = rQStartDateTime;
            BPiaoBao.DomesticTicket.Platforms._baiTuo.GetAlterCommonFileStreamPolicyResponse retVal = ((BPiaoBao.DomesticTicket.Platforms._baiTuo.BaitourServiceSoap)(this)).GetAlterCommonFileStreamPolicy(inValue);
            return retVal.GetAlterCommonFileStreamPolicyResult;
        }
        
        public string GetAlterCommonPolicy(string tripType, string ticketType, string agentUserName, string pwd, string rQStartDateTime) {
            return base.Channel.GetAlterCommonPolicy(tripType, ticketType, agentUserName, pwd, rQStartDateTime);
        }
        
        public string MatchCommonPolicy(string xmlDoc) {
            return base.Channel.MatchCommonPolicy(xmlDoc);
        }
        
        public string MatchCommonPolicyNew(string xmlDoc) {
            return base.Channel.MatchCommonPolicyNew(xmlDoc);
        }
        
        public string GetAVPolicy(string xmlDoc) {
            return base.Channel.GetAVPolicy(xmlDoc);
        }
        
        public string GetDomesticMatchNormalZRateByID(string xmlDoc) {
            return base.Channel.GetDomesticMatchNormalZRateByID(xmlDoc);
        }
        
        public string DetailCreateOrder(string xmlDoc) {
            return base.Channel.DetailCreateOrder(xmlDoc);
        }
        
        public string RTCreateOrder(string xmlDoc) {
            return base.Channel.RTCreateOrder(xmlDoc);
        }
        
        public System.Xml.XmlNode ChdDetailCreateOrder(string xmlDoc) {
            return base.Channel.ChdDetailCreateOrder(xmlDoc);
        }
        
        public string GetOrderInfo(string AgentCode, string AgentUserName, string AgentPwd, string OrderID) {
            return base.Channel.GetOrderInfo(AgentCode, AgentUserName, AgentPwd, OrderID);
        }
        
        public string GetInvalidationProviders(string AgentCode, string AgentUserName, string AgentPwd) {
            return base.Channel.GetInvalidationProviders(AgentCode, AgentUserName, AgentPwd);
        }
        
        public string RefundOrder(string xmlDoc) {
            return base.Channel.RefundOrder(xmlDoc);
        }
        
        public string GetChangeFlightDate(string xmlDoc) {
            return base.Channel.GetChangeFlightDate(xmlDoc);
        }
    }
}
