//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.19075
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPiaoBao.DomesticTicket.Platforms.webTodayAutoPay {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="webTodayAutoPay.JinRiAutoPayServerSoap")]
    public interface JinRiAutoPayServerSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutoPayOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string AutoPayOrder(string xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface JinRiAutoPayServerSoapChannel : BPiaoBao.DomesticTicket.Platforms.webTodayAutoPay.JinRiAutoPayServerSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class JinRiAutoPayServerSoapClient : System.ServiceModel.ClientBase<BPiaoBao.DomesticTicket.Platforms.webTodayAutoPay.JinRiAutoPayServerSoap>, BPiaoBao.DomesticTicket.Platforms.webTodayAutoPay.JinRiAutoPayServerSoap {
        
        public JinRiAutoPayServerSoapClient() {
        }
        
        public JinRiAutoPayServerSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public JinRiAutoPayServerSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JinRiAutoPayServerSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public JinRiAutoPayServerSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string AutoPayOrder(string xml) {
            return base.Channel.AutoPayOrder(xml);
        }
    }
}
