//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.19075
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPiaoBao.DomesticTicket.Platforms.webpm {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://203.88.210.234:116/PMService.asmx", ConfigurationName="webpm.PMServiceSoap")]
    public interface PMServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:116/PMService.asmx/GetPolicyDataByDC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPolicyDataByDC(string Date, string Flightno, string FromCityCode, string ToCityCode, string dataFormat, string Seat, string UID, string PWD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:116/PMService.asmx/NewGetPolicyDataByDC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet NewGetPolicyDataByDC(string PnrType, string Date, string Flightno, string FromCityCode, string ToCityCode, string dataFormat, string Seat, string UID, string PWD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:116/PMService.asmx/GetPolicyDataByWFLC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetPolicyDataByWFLC(string Type, string Date, string Date2, string Flightno, string Flightno2, string FromCityCode, string FromCityCode2, string ToCityCode, string ToCityCode2, string dataFormat, string Seat, string Seat2, string UID, string PWD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:116/PMService.asmx/NewGetPolicyDataByWFLC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet NewGetPolicyDataByWFLC(string PnrType, string Type, string Date, string Date2, string Flightno, string Flightno2, string FromCityCode, string FromCityCode2, string ToCityCode, string ToCityCode2, string dataFormat, string Seat, string Seat2, string UID, string PWD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:116/PMService.asmx/CreateOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CreateOrder(string PolicyID, string PnrCode, string UID, string PWD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:116/PMService.asmx/CreateOrderByPAT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CreateOrderByPAT(string policyID, string bigPNR, string rtData, string patData, string isChild, string UID, string PWD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:116/PMService.asmx/PMPay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet PMPay(string OrderID, string UID, string PWD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:116/PMService.asmx/PMOrderQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet PMOrderQuery(string OrderID, string UID, string PWD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:116/PMService.asmx/PMOrderTF", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet PMOrderTF(string OrderID, string Ticketno, string Status, string Comment, string Refoundfee, string UID, string PWD);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PMServiceSoapChannel : BPiaoBao.DomesticTicket.Platforms.webpm.PMServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PMServiceSoapClient : System.ServiceModel.ClientBase<BPiaoBao.DomesticTicket.Platforms.webpm.PMServiceSoap>, BPiaoBao.DomesticTicket.Platforms.webpm.PMServiceSoap {
        
        public PMServiceSoapClient() {
        }
        
        public PMServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PMServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PMServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PMServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetPolicyDataByDC(string Date, string Flightno, string FromCityCode, string ToCityCode, string dataFormat, string Seat, string UID, string PWD) {
            return base.Channel.GetPolicyDataByDC(Date, Flightno, FromCityCode, ToCityCode, dataFormat, Seat, UID, PWD);
        }
        
        public System.Data.DataSet NewGetPolicyDataByDC(string PnrType, string Date, string Flightno, string FromCityCode, string ToCityCode, string dataFormat, string Seat, string UID, string PWD) {
            return base.Channel.NewGetPolicyDataByDC(PnrType, Date, Flightno, FromCityCode, ToCityCode, dataFormat, Seat, UID, PWD);
        }
        
        public System.Data.DataSet GetPolicyDataByWFLC(string Type, string Date, string Date2, string Flightno, string Flightno2, string FromCityCode, string FromCityCode2, string ToCityCode, string ToCityCode2, string dataFormat, string Seat, string Seat2, string UID, string PWD) {
            return base.Channel.GetPolicyDataByWFLC(Type, Date, Date2, Flightno, Flightno2, FromCityCode, FromCityCode2, ToCityCode, ToCityCode2, dataFormat, Seat, Seat2, UID, PWD);
        }
        
        public System.Data.DataSet NewGetPolicyDataByWFLC(string PnrType, string Type, string Date, string Date2, string Flightno, string Flightno2, string FromCityCode, string FromCityCode2, string ToCityCode, string ToCityCode2, string dataFormat, string Seat, string Seat2, string UID, string PWD) {
            return base.Channel.NewGetPolicyDataByWFLC(PnrType, Type, Date, Date2, Flightno, Flightno2, FromCityCode, FromCityCode2, ToCityCode, ToCityCode2, dataFormat, Seat, Seat2, UID, PWD);
        }
        
        public System.Data.DataSet CreateOrder(string PolicyID, string PnrCode, string UID, string PWD) {
            return base.Channel.CreateOrder(PolicyID, PnrCode, UID, PWD);
        }
        
        public System.Data.DataSet CreateOrderByPAT(string policyID, string bigPNR, string rtData, string patData, string isChild, string UID, string PWD) {
            return base.Channel.CreateOrderByPAT(policyID, bigPNR, rtData, patData, isChild, UID, PWD);
        }
        
        public System.Data.DataSet PMPay(string OrderID, string UID, string PWD) {
            return base.Channel.PMPay(OrderID, UID, PWD);
        }
        
        public System.Data.DataSet PMOrderQuery(string OrderID, string UID, string PWD) {
            return base.Channel.PMOrderQuery(OrderID, UID, PWD);
        }
        
        public System.Data.DataSet PMOrderTF(string OrderID, string Ticketno, string Status, string Comment, string Refoundfee, string UID, string PWD) {
            return base.Channel.PMOrderTF(OrderID, Ticketno, Status, Comment, Refoundfee, UID, PWD);
        }
    }
}
