//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.19075
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPiaoBao.DomesticTicket.Platforms.web517 {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://203.88.210.234:115/517WebService.asmx", ConfigurationName="web517._517WebServiceSoap")]
    public interface _517WebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:115/517WebService.asmx/GetBenefitDataPnrContent", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetBenefitDataPnrContent(string UserName, string UserPwd, string AgentSine, string PNRContent, string PatContent, string PNRCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:115/517WebService.asmx/CreateOrderByPnrAndPAT", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CreateOrderByPnrAndPAT(string UserName, string UserPwd, string AgentSine, string PnrContent, string BigPnr, int BenefitID, string Linker, string LinkTel, string SplitBenefitID, string PatContent, string PNRCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:115/517WebService.asmx/CreateOrderByPnrAndPATCeshi", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CreateOrderByPnrAndPATCeshi(string UserName, string UserPwd, string AgentSine, string PnrContent, string BigPnr, int BenefitID, string Linker, string LinkTel, string SplitBenefitID, string PatContent, string PNRCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:115/517WebService.asmx/CreateOrderByPnrAndPATNew", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CreateOrderByPnrAndPATNew(string UserName, string UserPwd, string AgentSine, string Account, string APWD, string PNRContent, string PATContent, string BigPNR, int PolicyID, string PolicyChildID, string PayPrice, string Linker, string LinkTel, string PNRCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:115/517WebService.asmx/OrderPay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet OrderPay(string UserName, string UserPwd, string AgentSine, string Account, string APWD, string OrderID, decimal Amount, string NotifyUrl, string PNRCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:115/517WebService.asmx/OrderNoPwdPay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet OrderNoPwdPay(string UserName, string UserPwd, string OrderID, decimal Amount, string AgentSine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:115/517WebService.asmx/GetOrderInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOrderInfo(string UserName, string UserPwd, string AgentSine, string OrderID, string PNRCode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:115/517WebService.asmx/GetOrders", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetOrders(string UserName, string UserPwd, string AgentSine, string status, string starttime, string endtime, string pnr, string orderid, string passenger, string maxcount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:115/517WebService.asmx/CancelOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CancelOrder(string UserName, string UserPwd, string AgentSine, string OrderID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:115/517WebService.asmx/RefundTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet RefundTicket(string UserName, string UserPwd, byte RefundType, string AgentSine, string XmlParameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:115/517WebService.asmx/NewRefundTicket", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet NewRefundTicket(string UserName, string UserPwd, string AgentSine, byte RefundType, string OrderId, string poundagedealtype, string passengertype, string reasonid, string reasondetails, string reasonremark, string PassengerInfo, string ExtendInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:115/517WebService.asmx/GetRefundReason", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetRefundReason(string UserName, string UserPwd, byte RefundType, string AgentSine);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:115/517WebService.asmx/GetTFTicketDetailInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetTFTicketDetailInfo(int QType, string UserName, string UserPwd, string AgentSine, string OrderId, string TicketNum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:115/517WebService.asmx/GetAllErrInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetAllErrInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://203.88.210.234:115/517WebService.asmx/GetUrlData", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUrlData(string url);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface _517WebServiceSoapChannel : BPiaoBao.DomesticTicket.Platforms.web517._517WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class _517WebServiceSoapClient : System.ServiceModel.ClientBase<BPiaoBao.DomesticTicket.Platforms.web517._517WebServiceSoap>, BPiaoBao.DomesticTicket.Platforms.web517._517WebServiceSoap {
        
        public _517WebServiceSoapClient() {
        }
        
        public _517WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public _517WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public _517WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public _517WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet GetBenefitDataPnrContent(string UserName, string UserPwd, string AgentSine, string PNRContent, string PatContent, string PNRCode) {
            return base.Channel.GetBenefitDataPnrContent(UserName, UserPwd, AgentSine, PNRContent, PatContent, PNRCode);
        }
        
        public System.Data.DataSet CreateOrderByPnrAndPAT(string UserName, string UserPwd, string AgentSine, string PnrContent, string BigPnr, int BenefitID, string Linker, string LinkTel, string SplitBenefitID, string PatContent, string PNRCode) {
            return base.Channel.CreateOrderByPnrAndPAT(UserName, UserPwd, AgentSine, PnrContent, BigPnr, BenefitID, Linker, LinkTel, SplitBenefitID, PatContent, PNRCode);
        }
        
        public System.Data.DataSet CreateOrderByPnrAndPATCeshi(string UserName, string UserPwd, string AgentSine, string PnrContent, string BigPnr, int BenefitID, string Linker, string LinkTel, string SplitBenefitID, string PatContent, string PNRCode) {
            return base.Channel.CreateOrderByPnrAndPATCeshi(UserName, UserPwd, AgentSine, PnrContent, BigPnr, BenefitID, Linker, LinkTel, SplitBenefitID, PatContent, PNRCode);
        }
        
        public System.Data.DataSet CreateOrderByPnrAndPATNew(string UserName, string UserPwd, string AgentSine, string Account, string APWD, string PNRContent, string PATContent, string BigPNR, int PolicyID, string PolicyChildID, string PayPrice, string Linker, string LinkTel, string PNRCode) {
            return base.Channel.CreateOrderByPnrAndPATNew(UserName, UserPwd, AgentSine, Account, APWD, PNRContent, PATContent, BigPNR, PolicyID, PolicyChildID, PayPrice, Linker, LinkTel, PNRCode);
        }
        
        public System.Data.DataSet OrderPay(string UserName, string UserPwd, string AgentSine, string Account, string APWD, string OrderID, decimal Amount, string NotifyUrl, string PNRCode) {
            return base.Channel.OrderPay(UserName, UserPwd, AgentSine, Account, APWD, OrderID, Amount, NotifyUrl, PNRCode);
        }
        
        public System.Data.DataSet OrderNoPwdPay(string UserName, string UserPwd, string OrderID, decimal Amount, string AgentSine) {
            return base.Channel.OrderNoPwdPay(UserName, UserPwd, OrderID, Amount, AgentSine);
        }
        
        public System.Data.DataSet GetOrderInfo(string UserName, string UserPwd, string AgentSine, string OrderID, string PNRCode) {
            return base.Channel.GetOrderInfo(UserName, UserPwd, AgentSine, OrderID, PNRCode);
        }
        
        public System.Data.DataSet GetOrders(string UserName, string UserPwd, string AgentSine, string status, string starttime, string endtime, string pnr, string orderid, string passenger, string maxcount) {
            return base.Channel.GetOrders(UserName, UserPwd, AgentSine, status, starttime, endtime, pnr, orderid, passenger, maxcount);
        }
        
        public System.Data.DataSet CancelOrder(string UserName, string UserPwd, string AgentSine, string OrderID) {
            return base.Channel.CancelOrder(UserName, UserPwd, AgentSine, OrderID);
        }
        
        public System.Data.DataSet RefundTicket(string UserName, string UserPwd, byte RefundType, string AgentSine, string XmlParameters) {
            return base.Channel.RefundTicket(UserName, UserPwd, RefundType, AgentSine, XmlParameters);
        }
        
        public System.Data.DataSet NewRefundTicket(string UserName, string UserPwd, string AgentSine, byte RefundType, string OrderId, string poundagedealtype, string passengertype, string reasonid, string reasondetails, string reasonremark, string PassengerInfo, string ExtendInfo) {
            return base.Channel.NewRefundTicket(UserName, UserPwd, AgentSine, RefundType, OrderId, poundagedealtype, passengertype, reasonid, reasondetails, reasonremark, PassengerInfo, ExtendInfo);
        }
        
        public System.Data.DataSet GetRefundReason(string UserName, string UserPwd, byte RefundType, string AgentSine) {
            return base.Channel.GetRefundReason(UserName, UserPwd, RefundType, AgentSine);
        }
        
        public System.Data.DataSet GetTFTicketDetailInfo(int QType, string UserName, string UserPwd, string AgentSine, string OrderId, string TicketNum) {
            return base.Channel.GetTFTicketDetailInfo(QType, UserName, UserPwd, AgentSine, OrderId, TicketNum);
        }
        
        public System.Data.DataSet GetAllErrInfo() {
            return base.Channel.GetAllErrInfo();
        }
        
        public string GetUrlData(string url) {
            return base.Channel.GetUrlData(url);
        }
    }
}
